Update React support information
dequelabs/axe-core-npm pull request #1004
Opened 2024-02-06 10:43 UTC by ballendq

Fixes #500.

2024-02-06 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dequelabs/axe-core-npm?pullRequest=1004) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dequelabs/axe-core-npm?pullRequest=1004) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dequelabs/axe-core-npm?pullRequest=1004) it.</sub>

2024-02-06 10:50 UTC, WilcoFiers requested changes

2024-02-06 10:50 UTC, WilcoFiers commented on packages/react/README.md
> +This package does not support React 18 and above. Deque are working on alternatives for React 18+ developers and will update the community following product announcements at [axe-con 2024](https://ww
```suggestion
This package does not support React 18 and above. Deque is working on alternatives for React 18+ developers and will update the community following product announcements at [axe-con 2024](https://www.deque.com/axe-con/).
```

2024-02-08 14:36 UTC, Zidious approved these changes
LGTM! - Just amended the PR title to scope the docs change to the react package

2024-02-09 14:07 UTC, merged