feat(react): add support for runOnly.
dequelabs/axe-core-npm pull request #101
Opened 2020-10-16 03:31 UTC by voidJuneau

Make separated ReactSpec interface to go around for support "runOnly".
Try to run the test, but could have not solved npm issues.
Enable below syntax
```
reactAxe(React, ReactDOM, 1000, {
      runOnly: ['wcag2aa', 'wcag2a']
    });
```
[react: add support for runOnly #93](https://github.com/dequelabs/axe-core-npm/issues/93)

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [ ] Code is reviewed for security

2020-11-12 14:57 UTC, michael-siek requested changes

2020-11-12 14:57 UTC, michael-siek commented on packages/react/index.ts
> +  conf?: reactSpec,
```suggestion
  conf?: ReactSpec,
```

2020-11-16 14:24 UTC, michael-siek commented
Hi @voidJuneau, thank you for your contribution. We are working towards a release of our axe-core-npm packages & would like your contribution to be a part of it, therefore we will take it over and get this actioned/ merged. Have a good day.

2020-11-17 01:36 UTC, jeeyyy approved these changes

2020-11-17 02:00 UTC, merged