Handle undefined config when not specified
dequelabs/axe-core-npm pull request #177
Opened 2020-12-02 19:33 UTC by geoffharcourt

`react-axe` will fail with an exception if the configuration object is
not specified in the call to `axe()`:

A call like this:

```es6
axe(React, ReactDOM, 3000)
```

Throws an error like this:

```
index.js:374 Uncaught TypeError: Cannot read property 'runOnly' of undefined
    at reactAxe (index.js:374)
```

The existence of the configuration object is checked lower down in the
function, but the early check to see if `runOnly` is relevant doesn't work if
the object isn't there.

A workaround is to specify an empty object `{}`, but it seems from the
type definitions that this is truly meant to be an optional parameter.

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [ ] Code is reviewed for security

2020-12-02 19:34 UTC, geoffharcourt commented on packages/react/index.ts
> +  const runOnly = (conf || {})['runOnly'];
We could alternately define a default argument of `{}` for `conf` on line 350, but I wasn't sure if the config call below would change with an empty object vs. skipping the call to `configure` completely.

2020-12-02 19:36 UTC, geoffharcourt commented on packages/react/test/index.ts
> +reactAxe(React, ReactDOM, 1000, {}, undefined)
The call on line 4 doesn't specify an argument, but the suite doesn't catch a failure.

2020-12-15 16:53 UTC, jeeyyy commented
@geoffharcourt could you please update your branch with the base branch & push. Thanks.

2020-12-15 17:14 UTC, geoffharcourt commented
@jeeyyy done!

2020-12-16 14:01 UTC, jeeyyy commented
@geoffharcourt it still says the branch is out of date. Could you please verify?

2020-12-16 14:05 UTC, geoffharcourt commented
@jeeyyy someone pushed new code since I rebased.

2020-12-16 14:18 UTC, geoffharcourt commented
@jeeyyy rebased and pushed

2020-12-18 15:56 UTC, jeeyyy requested changes
@geoffharcourt for some reason the CircleCI workflow for this branch is not triggered. 
It seems like the forked PR does not display in the upstream repo. 

For example here is another [contribution PR](https://github.com/dequelabs/axe-core-npm/pull/181) which seems to have the [pipeline in CircleCI](https://app.circleci.com/pipelines/github/dequelabs/axe-core-npm?branch=pull%2F181)

But for this tree the link is not found - https://app.circleci.com/pipelines/github/dequelabs/axe-core-npm?branch=pull%2F177

Here are some [debug notes](https://discuss.circleci.com/t/fork-pull-request-build-did-not-display-in-upstream-repo/29648)

Could you check/ push a dummy commit to see if Circle CI runs. Thanks.

2020-12-18 16:05 UTC, geoffharcourt commented
Hi, this is really growing to be an outsized investment to help fix a bug. We will just work with the workaround instead of fixing the code.

2020-12-18 16:05 UTC, closed without merging