chore: add security review
dequelabs/axe-core-npm pull request #227
Opened 2021-04-20 17:36 UTC by michael-siek

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [ ] Code is reviewed for security

2021-04-20 21:28 UTC, stephenmathieson requested changes
You need to enable the app first.

2021-04-22 14:52 UTC, stephenmathieson commented
@michael-siek please push a new commit so the bot shows up here.

2021-04-27 16:00 UTC, stephenmathieson commented
I don't see the security check listed here? 🤔

2021-04-27 16:41 UTC, straker approved these changes

2021-04-27 16:43 UTC, straker approved these changes

2021-04-27 16:49 UTC, merged