fix(cli): find axe-core when installed globally
dequelabs/axe-core-npm pull request #232
Opened 2021-04-26 15:43 UTC by michael-siek

See: #229 
This issue only happens when installing `@axe-core/cli` globally. 

## Reviewer checks

**Required fields, to be filled out by PR reviewer(s)**

- [ ] Code is reviewed for security

2021-04-26 17:37 UTC, stephenmathieson requested changes
I think we could better solve this using Node's module lookup algorithm.

```
axe_core_file_path = require.resolve('axe-core')
```

This will return the _nearest_ installed axe-core. It works both when installed globally and as a project dependency.

2021-04-27 11:11 UTC, WilcoFiers submitted a review, later dismissed
Tests

2021-04-27 18:36 UTC, stephenmathieson commented
Writing a proper test for this will be difficult. To actually reproduce the problem, we'd have to globally install the program and run it. Not really something that qualities as a "unit test" IMO. Furthermore, we're using Node's algorithm now, which we already assume works (otherwise, nothing here would). Since the existing tests pass, and this is _removing_ custom logic and replacing it with Node's `require`, do we really need to setup an E2E test for this?

2021-04-28 13:06 UTC, WilcoFiers requested changes

2021-04-28 13:06 UTC, WilcoFiers commented on packages/cli/src/lib/utils.test.ts
> +        assert.isNotNull(axeSource);
I'm not sure what this is supposed to prove, but just asserting that it isn't null doesn't mean much.

2021-04-29 15:10 UTC, WilcoFiers approved these changes

2021-04-29 15:12 UTC, merged