feat(playwright): Upgrade to axe-core@4.3.2
dequelabs/axe-core-npm pull request #334
Opened 2021-08-17 00:27 UTC by michael-siek

2021-08-17 14:04 UTC, WilcoFiers requested changes

2021-08-17 14:42 UTC, michael-siek commented on packages/playwright/src/index.ts
> +        ).contentFrame();
This is a typeof `Frame`

2021-08-17 14:43 UTC, michael-siek commented on packages/playwright/src/index.ts
>    public async analyze(): Promise<AxeResults> {
https://github.com/dequelabs/axe-devtools-npm/pull/1127#issue-596040288

2021-08-18 17:10 UTC, straker approved these changes
LGTM. Do we need Wilco to approve his one comment? https://github.com/dequelabs/axe-core-npm/pull/334/files#r690399615

2021-08-18 17:10 UTC, straker submitted a review, later dismissed
Sorry, forgot I had a change marked

2021-08-18 19:34 UTC, WilcoFiers commented on packages/playwright/src/index.ts
>    public async analyze(): Promise<AxeResults> {
If we do need to change it, it should be in a separate PR. Don't let that hold this up.

2021-08-18 19:41 UTC, straker approved these changes

2021-08-18 19:45 UTC, merged