chore: test axe.runPartial deepEqual axe.run
dequelabs/axe-core-npm pull request #341
Opened 2021-08-25 17:14 UTC by WilcoFiers

2021-08-30 16:33 UTC, straker submitted a review, later dismissed

2021-08-30 16:33 UTC, straker commented on packages/playwright/tests/axe-playwright.spec.ts
> +    `${externalPath}/axe-core@legacy.js`,
This path structure could fail on windows

```suggestion
    path.join(externalPath, 'axe-core@legacy.js'),
```

2021-08-30 16:33 UTC, straker commented on packages/playwright/tests/axe-playwright.spec.ts
> +    `${externalPath}/axe-crasher.js`,
```suggestion
    path.join(externalPath, 'axe-crasher.js')
```

2021-08-30 16:33 UTC, straker commented on packages/playwright/tests/axe-playwright.spec.ts
> +    `${externalPath}/axe-force-legacy.js`,
```suggestion
    path.join(externalPath, 'axe-force-legacy.js'),
```

2021-08-30 16:33 UTC, straker commented on packages/puppeteer/test/axePuppeteer.test.ts
> +    const externalPath = path.resolve(__dirname, './fixtures/external/');
```suggestion
    const externalPath = path.join(__dirname, 'fixtures', 'external');
```

2021-08-30 16:33 UTC, straker commented on packages/puppeteer/test/axePuppeteer.test.ts
> +      `${externalPath}/axe-crasher.js`,
```suggestion
      path.join(externalPath, 'axe-crasher.js'),
```

2021-08-30 16:33 UTC, straker commented on packages/puppeteer/test/axePuppeteer.test.ts
> +      `${externalPath}/axe-force-legacy.js`,
```suggestion
      path.join(externalPath, 'axe-force-legacy.js'),
```

2021-08-30 16:33 UTC, straker commented on packages/webdriverio/src/test.ts
> +      `${axeTestFixtures}/axe-crasher.js`,
```suggestion
      path.join(axeTestFixtures, 'axe-crasher.js'),
```

2021-08-30 16:33 UTC, straker commented on packages/webdriverio/src/test.ts
> +      `${axeTestFixtures}/axe-force-legacy.js`,
```suggestion
      path.join(axeTestFixtures, 'axe-force-legacy.js'),
```

2021-08-31 22:21 UTC, straker requested changes

2021-08-31 22:21 UTC, straker commented on packages/playwright/tests/axe-playwright.spec.ts
> +    });
Don't need to run the test twice

```suggestion
```

2021-08-31 22:21 UTC, straker commented on packages/puppeteer/test/axePuppeteer.test.ts
> +    });
Don't need to run the test twice

```suggestion
```

2021-08-31 22:21 UTC, straker commented on packages/webdriverio/src/test.ts
> +        });
Don't need to run the test twice

```suggestion
```

2021-08-31 22:21 UTC, straker commented on packages/puppeteer/test/axePuppeteer.test.ts
> +    const externalPath = path.resolve(__dirname, './fixtures/external/');
This is still there

2021-09-03 15:18 UTC, straker submitted a review, later dismissed

2021-09-07 21:16 UTC, straker commented
Looks like you might need to update from latest again to get chromedriver changes https://github.com/dequelabs/axe-core-npm/pull/355

2021-09-09 19:09 UTC, michael-siek approved these changes

2021-09-09 19:15 UTC, merged