Add uploading of include and exclude from multi string array fixing #398
dequelabs/axe-core-npm pull request #413
Opened 2021-12-16 22:46 UTC by Bracciata

2021-12-22 14:03 UTC, michael-siek commented
Thank you very much for your contribution!

2021-12-23 15:02 UTC, Zidious requested changes
Hey @Bracciata! 

Thanks for contributing, unfortunately the issue I created was not quite correct. The current include / exclude selectors I put in the issue [ticket](https://github.com/dequelabs/axe-core-npm/issues/398) show iframe selectors and not the correct layout for include/excluding whom parent include said classes as shown in in the axe-core example:

> Include the whole document except any structures whose parent contains the class `exclude1` or `exclude2`. the structure would need to look like: 

```js
const builder = new AxeBuilder()
  .exclude([ ['.exclude1'], ['.exclude2'] ])
  ```

2021-12-23 15:04 UTC, Zidious commented on packages/playwright/tests/axe-playwright.spec.ts
> -      assert.deepEqual(actual[0], expected);
We would need to keep this test, it checks that the selectors are getting passed to axe-core

2021-12-23 15:06 UTC, Zidious commented on packages/playwright/tests/axe-playwright.spec.ts
> -      assert.deepEqual(actual[0], expected);
We would need to keep this exclude test, it checks that the exclude selectors are getting passed to axe-core

2022-01-01 20:57 UTC, Bracciata commented
@Zidious What are your thoughts on fully flattening the array then appending?

2022-01-05 20:09 UTC, Zidious commented
> @Zidious What are your thoughts on fully flattening the array then appending?

@Bracciata Thanks for getting back to me! I believe that will not work as its how it gets passed to axe-core. Currently, we allow chaining of include/exclude which produces the correct array format, example: 

```js
const builder = new AxeBuilder()
  .exclude('.exclude1')
  .exclude('.exclude2')
  
  // When produces this when passed to axe-core: { exclude: [ [ '.exclude' ], [ '.exclude2' ] ] }
```
So we would need to mimic the same behaviour, leave it with me, I will need to discuss it further with the team and I will get back to you ASAP.

2022-01-07 15:56 UTC, Zidious commented
@Bracciata Sorry to keep you waiting, had a discussion with the team due to how the include / exclude array is passed to axe-core it would require a significant amount of changes. We have decided to keep the current include / exclude chaining for classes (See below): 

```js
const builder = new AxeBuilder()
  .exclude('.exclude1')
  .exclude('.exclude2')
  ```

2022-01-07 15:56 UTC, closed without merging