fix: playwright, puppteer, WDIO, and, WDJS tests
dequelabs/axe-core-npm pull request #499
Opened 2022-04-07 13:54 UTC by Zidious

Mostly, the pathing of the test fixtures were incorrect, so it was not testing the correct page.

2022-04-07 16:25 UTC, straker submitted a review, later dismissed
Since this problem was caused by us not realizing that the pages we navigated to were returning 404s, I think we should take the extra time here and assert that the page is what we expect before running tests. Something like assert the title of the page or the status of the page should be sufficient.

```js
const title = await page.title();
asset.equal(title, 'Nested Frames')

// or

const response = await page.goto(url);
asset.equal(response.status(), 200) 
```


_Edit:_ I think asserting the status is probably the better solution

2022-04-07 19:16 UTC, Zidious commented
Unfortunately, [WDJS](https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/ie_exports_Driver.html#get)' `get` returns `undefined`, doesn't appear to be a way to get the status code of a page (technically the page loaded, just with a 404). 

Similarly, WDIO `url` returns a `string[]` which incorrect url path or not returns `null`, doesn't appear to be a way to check the status here either.

2022-04-08 16:00 UTC, straker requested changes
For wdjs and wdio you can assert that the `title` isn't `"Error"`.

```js
await client.url(`${addr}/doesnt-exist-frameset.html`);
const title = await client.getTitle();  // { title: 'Error' }
assert.notEqual(title, 'Error');
```

2022-04-08 16:00 UTC, straker commented on packages/playwright/tests/axe-playwright.spec.ts
> +      const res = await page.goto(`${addr}/external/index.html`);
`res` isn't used in the test. surprised that didn't throw a lint error for unused variable.

2022-04-08 16:00 UTC, straker commented on packages/playwright/tests/axe-playwright.spec.ts
> +      const res = await page.goto(`${addr}/external/crash-parent.html`);
Not used here either

2022-04-08 16:00 UTC, straker commented on packages/playwright/tests/axe-playwright.spec.ts
> +      const res = await page.goto(`${addr}/context.html`);
Oy! mate! use res ("here too" in British English)

2022-04-08 16:00 UTC, straker commented on packages/puppeteer/test/axePuppeteer.test.ts
> +        // gotoP.catch(() => ({})); // suppress Node error
Should this be uncommented now?

2022-04-08 16:00 UTC, straker commented on packages/puppeteer/test/axePuppeteer.test.ts
> +        const res = await page.goto(`${addr}/context.html`);
aquí también ("here too" in Spanish)

2022-04-11 14:19 UTC, straker submitted a review, later dismissed

2022-04-11 14:19 UTC, straker commented on packages/webdriverjs/tests/axe-webdriverjs.spec.ts
> +          });
This is a race condition since the  code isn't waiting for the response  before going to the analyze.

2022-04-11 14:19 UTC, straker commented on packages/webdriverjs/tests/axe-webdriverjs.spec.ts
> +          driver.getTitle().then(res => {
Here too

2022-04-11 14:19 UTC, straker commented on packages/webdriverjs/tests/axe-webdriverjs.spec.ts
> +          driver.getTitle().then(res => {
Here too

2022-04-13 15:12 UTC, straker approved these changes

2022-04-13 15:15 UTC, merged