feat: update to use `axe-core@4.6.0`
dequelabs/axe-core-npm pull request #619
Opened 2022-12-12 21:39 UTC by michael-siek

2022-12-13 14:33 UTC, stephenmathieson requested changes
Why was https://github.com/dequelabs/axe-core-npm/actions/workflows/update-axe-core.yml not used?

2022-12-13 15:08 UTC, michael-siek commented
Because we also needed to add shadow dom selector changes

2022-12-13 15:12 UTC, stephenmathieson commented
> Because we also needed to add shadow dom selector changes

That should be in its own commit.

2022-12-13 17:43 UTC, straker submitted a review, later dismissed
The type changes and tests all look correct.

2022-12-13 17:43 UTC, straker commented on packages/playwright/src/index.ts
> +    console.log(JSON.stringify(context, null, 2));
```suggestion
```

2022-12-13 17:43 UTC, straker commented on packages/webdriverjs/src/utils/index.ts
>    const base: ContextObject = {
Hu, does this work? I thought we had to make everything a `SerialContextObject`

2022-12-15 15:40 UTC, straker requested changes

2022-12-15 15:40 UTC, straker commented on packages/playwright/src/index.ts
> +type NewContextObject = ContextObject | SerialContextObject;
This doesn't appear to be used anywhere

```suggestion
```

2022-12-15 16:05 UTC, straker approved these changes

2022-12-15 16:17 UTC, merged