fix(webdriverio): fix types between v8 and <v8
dequelabs/axe-core-npm pull request #962
Opened 2023-12-20 22:20 UTC by straker

This change brings the types from webdriverio v8 and makes the compatible with the types from <= v7. This change also prepares us to take the latest webdriverio v8 type changes which were causing our builds to break.

This also downgrades the version of @wdio packages in the wdio-globals test in order to not have multiple copies across packages. We should update all these types together so they don't go out-of-sync.

2023-12-20 22:48 UTC, straker commented on .github/workflows/tests.yml
> +        run: npx browser-driver-manager install chromedriver=119 --verbose
This is a temporary fix that will be fix in a separate pr to fix the cli tests with 120 https://github.com/dequelabs/axe-core-npm/issues/963.

2023-12-21 00:34 UTC, straker commented on packages/webdriverio/src/index.ts
> +    (this.client as WebdriverIO.Browser).setTimeout({
This fixes a problem with older versions of webdriverio as in newer versions they declare the function with the first parameter as [this: Webdriverio.Browser](https://github.com/webdriverio/webdriverio/blob/main/packages/webdriverio/src/commands/browser/setTimeout.ts#L40).

2023-12-21 00:34 UTC, straker commented on packages/webdriverio/src/utils.ts
> -      .executeAsync<string, []>(
Older versions of webdriverio [don't declare the type](https://github.com/webdriverio/webdriverio/blob/v6.12.1/packages/webdriverio/src/commands/browser/executeAsync.ts#L46) of the return so we can't declare it either. This defaults to `<unknown, []>` for the type in newer versions which is why we need to make the change below to make the string type `unknown` and then cast it to a `string`

2023-12-21 16:14 UTC, Zidious requested changes
Looking good, just a few minor comments inline -

2023-12-21 16:14 UTC, Zidious commented on packages/webdriverio/src/utils.ts
> +      .then((r: unknown) => deserialize<AxeResults>(r as string))
nit - this doesn't need to be cast as `unknown` it's already that type

2023-12-21 16:16 UTC, straker commented on packages/webdriverio/src/types.ts
> +    >;
No. It needs to be picked as there are incompatible types between the two. Luckily they are incompatible in functions we don't use so we can just pick them out.

2023-12-21 16:27 UTC, Zidious approved these changes
LGTM!

2023-12-21 16:27 UTC, merged